CREATE TABLE IF NOT EXISTS success_stories (
  id                INT AUTO_INCREMENT PRIMARY KEY,
  user_id           INT NOT NULL,
  groom_name        VARCHAR(150) NOT NULL,
  bride_name        VARCHAR(150) NOT NULL,
  couple_photo      VARCHAR(500),
  wedding_gallery   TEXT,
  wedding_date      DATE,
  wedding_location  VARCHAR(255),
  community         VARCHAR(100),
  story_title       VARCHAR(255) NOT NULL,
  short_description TEXT NOT NULL,
  full_story        TEXT NOT NULL,
  video_url         VARCHAR(500),
  consent           TINYINT(1) DEFAULT 0,
  status            ENUM('pending','approved','rejected') DEFAULT 'pending',
  rejection_remark  TEXT,
  reviewed_by       INT,
  submitted_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  approved_at       TIMESTAMP NULL,
  updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
);
