const mysql = require('mysql2/promise');
const bcrypt = require('bcryptjs');
require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });

const SALT_ROUNDS = 10;

const rasis = ['Mesha (Aries)', 'Vrishabha (Taurus)', 'Mithuna (Gemini)', 'Karka (Cancer)', 'Simha (Leo)', 'Kanya (Virgo)', 'Tula (Libra)', 'Vrishchika (Scorpio)', 'Dhanu (Sagittarius)', 'Makara (Capricorn)', 'Kumbha (Aquarius)', 'Meena (Pisces)'];
const nakshatras = ['Ashwini', 'Bharani', 'Krittika', 'Rohini', 'Mrigashira', 'Ardra', 'Punarvasu', 'Pushya', 'Ashlesha', 'Magha', 'Purva Phalguni', 'Uttara Phalguni', 'Hasta', 'Chitra', 'Swati', 'Vishakha', 'Anuradha', 'Jyeshtha', 'Mula', 'Purva Ashadha', 'Uttara Ashadha', 'Shravana', 'Dhanishtha', 'Shatabhisha', 'Purva Bhadrapada', 'Uttara Bhadrapada', 'Revati'];
const laknams = ['Mesha', 'Vrishabha', 'Mithuna', 'Karka', 'Simha', 'Kanya', 'Tula', 'Vrishchika', 'Dhanu', 'Makara', 'Kumbha', 'Meena'];
const gothrams = ['Kashyapa', 'Bharadwaja', 'Angirasa', 'Vasishta', 'Atri', 'Shandilya', 'Gautama', 'Jamadagni', 'Vishwamitra', 'Bhrigu', 'Parashara', 'Kaushika', 'Shounaka', 'Harita', 'Maitreya', 'Garga'];
const dhoshams = ['None', 'Manglik / Chevvai Dhosham', 'Sarpa Dhosham'];

const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];

const seedData = [
  {
    firstName: 'Arun', lastName: 'Kumar', email: 'arun@test.com', mobile: '9876543210',
    gender: 'male',
    fullName: 'Arun Kumar', age: 28, height: '5\'10"', weight: '72',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Iyer', subCaste: 'Vadama', motherTongue: 'Tamil',
    education: 'B.Tech Computer Science', occupation: 'Software Engineer', companyName: 'Google', annualIncome: '₹25 Lakhs',
    fatherName: 'Rajagopal', motherName: 'Lakshmi', siblings: 1,
    country: 'India', state: 'Tamil Nadu', city: 'Chennai',
    dateOfBirth: '1996-04-15', timeOfBirth: '06:45', placeOfBirth: 'Chennai',
    rasi: 'Mesha (Aries)', nakshatra: 'Ashwini', laknam: 'Simha', gothram: 'Kashyapa', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Kanya (Virgo)', 'Vrishchika (Scorpio)'],
    preferredNakshatra: ['Hasta', 'Jyeshtha'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 24, prefAgeMax: 30, prefHeight: '5\'4" - 5\'8"', prefEducation: 'Graduate', prefLocation: 'Chennai', prefReligion: 'Hindu',
  },
  {
    firstName: 'Priya', lastName: 'Sharma', email: 'priya@test.com', mobile: '9876543211',
    gender: 'female',
    fullName: 'Priya Sharma', age: 26, height: '5\'5"', weight: '58',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Sharma', subCaste: 'Kayastha', motherTongue: 'Hindi',
    education: 'MBA Marketing', occupation: 'Marketing Manager', companyName: 'Hindustan Unilever', annualIncome: '₹18 Lakhs',
    fatherName: 'Ravi Sharma', motherName: 'Sunita Sharma', siblings: 1,
    country: 'India', state: 'Delhi', city: 'New Delhi',
    dateOfBirth: '1998-09-22', timeOfBirth: '14:30', placeOfBirth: 'New Delhi',
    rasi: 'Kanya (Virgo)', nakshatra: 'Hasta', laknam: 'Mithuna', gothram: 'Bharadwaja', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Mesha (Aries)', 'Simha (Leo)', 'Dhanu (Sagittarius)'],
    preferredNakshatra: ['Ashwini', 'Magha', 'Mula'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 27, prefAgeMax: 33, prefHeight: '5\'8" - 6\'0"', prefEducation: 'Post Graduate', prefLocation: 'Delhi', prefReligion: 'Hindu',
  },
  {
    firstName: 'Rahul', lastName: 'Verma', email: 'rahul@test.com', mobile: '9876543212',
    gender: 'male',
    fullName: 'Rahul Verma', age: 30, height: '5\'11"', weight: '78',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Verma', subCaste: 'Kashyap', motherTongue: 'Hindi',
    education: 'CA', occupation: 'Chartered Accountant', companyName: 'Deloitte', annualIncome: '₹30 Lakhs',
    fatherName: 'Suresh Verma', motherName: 'Meena Verma', siblings: 0,
    country: 'India', state: 'Maharashtra', city: 'Mumbai',
    dateOfBirth: '1994-07-10', timeOfBirth: '09:15', placeOfBirth: 'Mumbai',
    rasi: 'Karka (Cancer)', nakshatra: 'Pushya', laknam: 'Tula', gothram: 'Angirasa', dhosham: 'Manglik / Chevvai Dhosham',
    horoscopeAvailable: true,
    preferredRasi: ['Vrishabha (Taurus)', 'Kanya (Virgo)', 'Makara (Capricorn)'],
    preferredNakshatra: ['Rohini', 'Hasta', 'Uttara Ashadha'],
    dhoshamPreference: 'Manglik / Chevvai Dhosham', horoscopeMatchRequired: true,
    prefAgeMin: 25, prefAgeMax: 30, prefHeight: '5\'3" - 5\'7"', prefEducation: 'Graduate', prefLocation: 'Mumbai', prefReligion: 'Hindu',
  },
  {
    firstName: 'Ananya', lastName: 'Reddy', email: 'ananya@test.com', mobile: '9876543213',
    gender: 'female',
    fullName: 'Ananya Reddy', age: 25, height: '5\'6"', weight: '55',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Reddy', subCaste: 'Goud', motherTongue: 'Telugu',
    education: 'MBBS', occupation: 'Doctor', companyName: 'Apollo Hospitals', annualIncome: '₹24 Lakhs',
    fatherName: 'Vijay Reddy', motherName: 'Padma Reddy', siblings: 2,
    country: 'India', state: 'Telangana', city: 'Hyderabad',
    dateOfBirth: '1999-11-05', timeOfBirth: '22:10', placeOfBirth: 'Hyderabad',
    rasi: 'Vrishchika (Scorpio)', nakshatra: 'Jyeshtha', laknam: 'Meena', gothram: 'Vasishta', dhosham: 'None',
    horoscopeAvailable: false,
    preferredRasi: ['Mesha (Aries)', 'Simha (Leo)'],
    preferredNakshatra: ['Ashwini', 'Magha'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 26, prefAgeMax: 32, prefHeight: '5\'7" - 6\'0"', prefEducation: 'Graduate', prefLocation: 'Hyderabad', prefReligion: 'Hindu',
  },
  {
    firstName: 'Vikram', lastName: 'Singh', email: 'vikram@test.com', mobile: '9876543214',
    gender: 'male',
    fullName: 'Vikram Singh', age: 32, height: '6\'0"', weight: '82',
    maritalStatus: 'Divorced', religion: 'Sikh', caste: 'Jatt', subCaste: 'Sikh', motherTongue: 'Punjabi',
    education: 'MBA Finance', occupation: 'Investment Banker', companyName: 'Goldman Sachs', annualIncome: '₹45 Lakhs',
    fatherName: 'Gurpreet Singh', motherName: 'Amandeep Kaur', siblings: 1,
    country: 'India', state: 'Punjab', city: 'Chandigarh',
    prefAgeMin: 26, prefAgeMax: 34, prefHeight: '5\'4" - 5\'9"', prefEducation: 'Graduate', prefLocation: 'Chandigarh', prefReligion: 'Any',
  },
  {
    firstName: 'Neha', lastName: 'Patel', email: 'neha@test.com', mobile: '9876543215',
    gender: 'female',
    fullName: 'Neha Patel', age: 27, height: '5\'4"', weight: '54',
    maritalStatus: 'Never Married', religion: 'Jain', caste: 'Patel', subCaste: 'Leva', motherTongue: 'Gujarati',
    education: 'B.Des Fashion Design', occupation: 'Fashion Designer', companyName: 'Self Employed', annualIncome: '₹15 Lakhs',
    fatherName: 'Mukesh Patel', motherName: 'Rekha Patel', siblings: 1,
    country: 'India', state: 'Gujarat', city: 'Ahmedabad',
    prefAgeMin: 28, prefAgeMax: 34, prefHeight: '5\'7" - 6\'1"', prefEducation: 'Graduate', prefLocation: 'Ahmedabad', prefReligion: 'Jain',
  },
  {
    firstName: 'Aditya', lastName: 'Joshi', email: 'aditya@test.com', mobile: '9876543216',
    gender: 'male',
    fullName: 'Aditya Joshi', age: 29, height: '5\'9"', weight: '70',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Joshi', subCaste: 'Gaud', motherTongue: 'Marathi',
    education: 'B.Arch', occupation: 'Architect', companyName: 'Studio 11 Architects', annualIncome: '₹20 Lakhs',
    fatherName: 'Dilip Joshi', motherName: 'Smita Joshi', siblings: 1,
    country: 'India', state: 'Maharashtra', city: 'Pune',
    dateOfBirth: '1995-12-18', timeOfBirth: '03:20', placeOfBirth: 'Pune',
    rasi: 'Dhanu (Sagittarius)', nakshatra: 'Mula', laknam: 'Dhanu', gothram: 'Atri', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Mithuna (Gemini)', 'Tula (Libra)', 'Kumbha (Aquarius)'],
    preferredNakshatra: ['Punarvasu', 'Swati', 'Dhanishtha'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 24, prefAgeMax: 30, prefHeight: '5\'2" - 5\'6"', prefEducation: 'Graduate', prefLocation: 'Pune', prefReligion: 'Hindu',
  },
  {
    firstName: 'Sara', lastName: 'Khan', email: 'sara@test.com', mobile: '9876543217',
    gender: 'female',
    fullName: 'Sara Khan', age: 24, height: '5\'3"', weight: '52',
    maritalStatus: 'Never Married', religion: 'Muslim', caste: 'Khan', subCaste: 'Pathan', motherTongue: 'Urdu',
    education: 'BA Psychology', occupation: 'HR Executive', companyName: 'Microsoft', annualIncome: '₹16 Lakhs',
    fatherName: 'Imran Khan', motherName: 'Zara Khan', siblings: 2,
    country: 'India', state: 'Karnataka', city: 'Bangalore',
    prefAgeMin: 26, prefAgeMax: 32, prefHeight: '5\'6" - 5\'11"', prefEducation: 'Graduate', prefLocation: 'Bangalore', prefReligion: 'Muslim',
  },
  {
    firstName: 'Karthik', lastName: 'Nair', email: 'karthik@test.com', mobile: '9876543218',
    gender: 'male',
    fullName: 'Karthik Nair', age: 31, height: '5\'8"', weight: '75',
    maritalStatus: 'Widowed', religion: 'Hindu', caste: 'Nair', subCaste: 'Moothan', motherTongue: 'Malayalam',
    education: 'MS Data Science', occupation: 'Data Scientist', companyName: 'Amazon', annualIncome: '₹35 Lakhs',
    fatherName: 'Ramesh Nair', motherName: 'Geetha Nair', siblings: 0,
    country: 'India', state: 'Kerala', city: 'Kochi',
    dateOfBirth: '1993-02-14', timeOfBirth: '11:00', placeOfBirth: 'Kochi',
    rasi: 'Kumbha (Aquarius)', nakshatra: 'Dhanishtha', laknam: 'Makara', gothram: 'Shandilya', dhosham: 'Sarpa Dhosham',
    horoscopeAvailable: true,
    preferredRasi: ['Karka (Cancer)', 'Vrishchika (Scorpio)'],
    preferredNakshatra: ['Ashlesha', 'Jyeshtha'],
    dhoshamPreference: 'Sarpa Dhosham', horoscopeMatchRequired: true,
    prefAgeMin: 25, prefAgeMax: 33, prefHeight: '5\'3" - 5\'8"', prefEducation: 'Post Graduate', prefLocation: 'Kochi', prefReligion: 'Hindu',
  },
  {
    firstName: 'Deepa', lastName: 'Banerjee', email: 'deepa@test.com', mobile: '9876543219',
    gender: 'female',
    fullName: 'Deepa Banerjee', age: 29, height: '5\'5"', weight: '56',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Banerjee', subCaste: 'Rarhi', motherTongue: 'Bengali',
    education: 'PhD Economics', occupation: 'Professor', companyName: 'IIT Kharagpur', annualIncome: '₹22 Lakhs',
    fatherName: 'Sourav Banerjee', motherName: 'Tanusree Banerjee', siblings: 1,
    country: 'India', state: 'West Bengal', city: 'Kolkata',
    dateOfBirth: '1997-03-28', timeOfBirth: '16:45', placeOfBirth: 'Kolkata',
    rasi: 'Meena (Pisces)', nakshatra: 'Revati', laknam: 'Karka', gothram: 'Gautama', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Simha (Leo)', 'Dhanu (Sagittarius)', 'Mesha (Aries)'],
    preferredNakshatra: ['Magha', 'Mula', 'Ashwini'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 30, prefAgeMax: 37, prefHeight: '5\'8" - 6\'2"', prefEducation: 'Post Graduate', prefLocation: 'Kolkata', prefReligion: 'Hindu',
  },
  // ─── 20 Additional Seed Profiles ───
  {
    firstName: 'Rohit', lastName: 'Mehta', email: 'rohit@test.com', mobile: '9876543220',
    gender: 'male', fullName: 'Rohit Mehta', age: 27, height: '5\'9"', weight: '71',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Mehta', subCaste: 'Khatri', motherTongue: 'Hindi',
    education: 'B.Com', occupation: 'Business Owner', companyName: 'Mehta Enterprises', annualIncome: '₹40 Lakhs',
    fatherName: 'Ramesh Mehta', motherName: 'Sushma Mehta', siblings: 1,
    country: 'India', state: 'Rajasthan', city: 'Jaipur',
    dateOfBirth: '1997-08-12', timeOfBirth: '07:30', placeOfBirth: 'Jaipur',
    rasi: 'Simha (Leo)', nakshatra: 'Magha', laknam: 'Simha', gothram: 'Kaushika', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Vrishabha (Taurus)', 'Kanya (Virgo)', 'Makara (Capricorn)'],
    preferredNakshatra: ['Rohini', 'Hasta', 'Uttara Ashadha'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 23, prefAgeMax: 29, prefHeight: '5\'2" - 5\'7"', prefEducation: 'Graduate', prefLocation: 'Jaipur', prefReligion: 'Hindu',
  },
  {
    firstName: 'Isha', lastName: 'Deshmukh', email: 'isha@test.com', mobile: '9876543221',
    gender: 'female', fullName: 'Isha Deshmukh', age: 24, height: '5\'5"', weight: '53',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Deshmukh', subCaste: 'Maratha', motherTongue: 'Marathi',
    education: 'LLB', occupation: 'Lawyer', companyName: 'Deshmukh & Associates', annualIncome: '₹12 Lakhs',
    fatherName: 'Sanjay Deshmukh', motherName: 'Nalini Deshmukh', siblings: 1,
    country: 'India', state: 'Maharashtra', city: 'Nagpur',
    dateOfBirth: '2000-02-18', timeOfBirth: '11:45', placeOfBirth: 'Nagpur',
    rasi: 'Mithuna (Gemini)', nakshatra: 'Punarvasu', laknam: 'Mithuna', gothram: 'Shounaka', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Simha (Leo)', 'Tula (Libra)', 'Kumbha (Aquarius)'],
    preferredNakshatra: ['Magha', 'Swati', 'Dhanishtha'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 26, prefAgeMax: 32, prefHeight: '5\'8" - 6\'0"', prefEducation: 'Post Graduate', prefLocation: 'Nagpur', prefReligion: 'Hindu',
  },
  {
    firstName: 'Amit', lastName: 'Saxena', email: 'amit@test.com', mobile: '9876543222',
    gender: 'male', fullName: 'Amit Saxena', age: 33, height: '5\'10"', weight: '76',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Saxena', subCaste: 'Kanyakubja', motherTongue: 'Hindi',
    education: 'MBBS MD', occupation: 'Doctor', companyName: 'AIIMS Delhi', annualIncome: '₹36 Lakhs',
    fatherName: 'Rajendra Saxena', motherName: 'Sudha Saxena', siblings: 1,
    country: 'India', state: 'Uttar Pradesh', city: 'Lucknow',
    dateOfBirth: '1991-11-30', timeOfBirth: '05:15', placeOfBirth: 'Lucknow',
    rasi: 'Tula (Libra)', nakshatra: 'Swati', laknam: 'Tula', gothram: 'Vishwamitra', dhosham: 'Manglik / Chevvai Dhosham',
    horoscopeAvailable: true,
    preferredRasi: ['Mithuna (Gemini)', 'Kumbha (Aquarius)', 'Simha (Leo)'],
    preferredNakshatra: ['Punarvasu', 'Dhanishtha', 'Magha'],
    dhoshamPreference: 'Manglik / Chevvai Dhosham', horoscopeMatchRequired: true,
    prefAgeMin: 25, prefAgeMax: 30, prefHeight: '5\'3" - 5\'8"', prefEducation: 'Graduate', prefLocation: 'Lucknow', prefReligion: 'Hindu',
  },
  {
    firstName: 'Kavya', lastName: 'Nambiar', email: 'kavya@test.com', mobile: '9876543223',
    gender: 'female', fullName: 'Kavya Nambiar', age: 26, height: '5\'6"', weight: '57',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Nambiar', subCaste: 'Nair', motherTongue: 'Malayalam',
    education: 'MCA', occupation: 'IT Consultant', companyName: 'Infosys', annualIncome: '₹14 Lakhs',
    fatherName: 'Mohan Nambiar', motherName: 'Girija Nambiar', siblings: 0,
    country: 'India', state: 'Kerala', city: 'Thiruvananthapuram',
    dateOfBirth: '1998-07-25', timeOfBirth: '14:00', placeOfBirth: 'Thiruvananthapuram',
    rasi: 'Kanya (Virgo)', nakshatra: 'Uttara Phalguni', laknam: 'Kanya', gothram: 'Parashara', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Vrishabha (Taurus)', 'Makara (Capricorn)', 'Kanya (Virgo)'],
    preferredNakshatra: ['Rohini', 'Uttara Ashadha', 'Uttara Phalguni'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 28, prefAgeMax: 34, prefHeight: '5\'7" - 6\'0"', prefEducation: 'Graduate', prefLocation: 'Thiruvananthapuram', prefReligion: 'Hindu',
  },
  {
    firstName: 'Manish', lastName: 'Agarwal', email: 'manish@test.com', mobile: '9876543224',
    gender: 'male', fullName: 'Manish Agarwal', age: 29, height: '5\'8"', weight: '68',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Agarwal', subCaste: 'Gupta', motherTongue: 'Hindi',
    education: 'MBA Finance', occupation: 'Investment Analyst', companyName: 'Morgan Stanley', annualIncome: '₹32 Lakhs',
    fatherName: 'Ashok Agarwal', motherName: 'Saroj Agarwal', siblings: 2,
    country: 'India', state: 'West Bengal', city: 'Kolkata',
    dateOfBirth: '1995-05-10', timeOfBirth: '08:30', placeOfBirth: 'Kolkata',
    rasi: 'Vrishabha (Taurus)', nakshatra: 'Rohini', laknam: 'Vrishabha', gothram: 'Bhrigu', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Kanya (Virgo)', 'Makara (Capricorn)', 'Mithuna (Gemini)'],
    preferredNakshatra: ['Hasta', 'Uttara Ashadha', 'Punarvasu'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 24, prefAgeMax: 30, prefHeight: '5\'3" - 5\'8"', prefEducation: 'Graduate', prefLocation: 'Kolkata', prefReligion: 'Hindu',
  },
  {
    firstName: 'Pooja', lastName: 'Rajput', email: 'pooja@test.com', mobile: '9876543225',
    gender: 'female', fullName: 'Pooja Rajput', age: 25, height: '5\'3"', weight: '52',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Rajput', subCaste: 'Chauhan', motherTongue: 'Hindi',
    education: 'B.Ed', occupation: 'Teacher', companyName: 'Delhi Public School', annualIncome: '₹7 Lakhs',
    fatherName: 'Vijay Rajput', motherName: 'Kavita Rajput', siblings: 2,
    country: 'India', state: 'Madhya Pradesh', city: 'Indore',
    dateOfBirth: '1999-09-14', timeOfBirth: '10:20', placeOfBirth: 'Indore',
    rasi: 'Karka (Cancer)', nakshatra: 'Pushya', laknam: 'Karka', gothram: 'Jamadagni', dhosham: 'None',
    horoscopeAvailable: false,
    preferredRasi: ['Mesha (Aries)', 'Simha (Leo)', 'Dhanu (Sagittarius)'],
    preferredNakshatra: ['Ashwini', 'Magha', 'Mula'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 27, prefAgeMax: 33, prefHeight: '5\'7" - 5\'11"', prefEducation: 'Graduate', prefLocation: 'Indore', prefReligion: 'Hindu',
  },
  {
    firstName: 'Siddharth', lastName: 'Chowdhury', email: 'siddharth@test.com', mobile: '9876543226',
    gender: 'male', fullName: 'Siddharth Chowdhury', age: 31, height: '5\'11"', weight: '80',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Chowdhury', subCaste: 'Baishya', motherTongue: 'Bengali',
    education: 'B.Tech Civil Engineering', occupation: 'Civil Engineer', companyName: 'L&T Construction', annualIncome: '₹18 Lakhs',
    fatherName: 'Partha Chowdhury', motherName: 'Mala Chowdhury', siblings: 1,
    country: 'India', state: 'Assam', city: 'Guwahati',
    dateOfBirth: '1993-03-22', timeOfBirth: '06:10', placeOfBirth: 'Guwahati',
    rasi: 'Makara (Capricorn)', nakshatra: 'Uttara Ashadha', laknam: 'Makara', gothram: 'Harita', dhosham: 'Sarpa Dhosham',
    horoscopeAvailable: true,
    preferredRasi: ['Vrishabha (Taurus)', 'Kanya (Virgo)', 'Mesha (Aries)'],
    preferredNakshatra: ['Rohini', 'Hasta', 'Ashwini'],
    dhoshamPreference: 'Sarpa Dhosham', horoscopeMatchRequired: true,
    prefAgeMin: 25, prefAgeMax: 31, prefHeight: '5\'2" - 5\'7"', prefEducation: 'Graduate', prefLocation: 'Guwahati', prefReligion: 'Hindu',
  },
  {
    firstName: 'Nandini', lastName: 'Iyer', email: 'nandini@test.com', mobile: '9876543227',
    gender: 'female', fullName: 'Nandini Iyer', age: 23, height: '5\'4"', weight: '50',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Iyer', subCaste: 'Brahadeeswaram', motherTongue: 'Tamil',
    education: 'B.Sc Nursing', occupation: 'Staff Nurse', companyName: 'Apollo Hospitals', annualIncome: '₹6 Lakhs',
    fatherName: 'Ramanathan Iyer', motherName: 'Parvathy Iyer', siblings: 1,
    country: 'India', state: 'Tamil Nadu', city: 'Madurai',
    dateOfBirth: '2001-01-08', timeOfBirth: '03:45', placeOfBirth: 'Madurai',
    rasi: 'Mesha (Aries)', nakshatra: 'Ashwini', laknam: 'Mesha', gothram: 'Kashyapa', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Kanya (Virgo)', 'Vrishchika (Scorpio)', 'Makara (Capricorn)'],
    preferredNakshatra: ['Hasta', 'Jyeshtha', 'Uttara Ashadha'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 25, prefAgeMax: 31, prefHeight: '5\'7" - 6\'0"', prefEducation: 'Graduate', prefLocation: 'Madurai', prefReligion: 'Hindu',
  },
  {
    firstName: 'Harsh', lastName: 'Shukla', email: 'harsh@test.com', mobile: '9876543228',
    gender: 'male', fullName: 'Harsh Shukla', age: 26, height: '5\'7"', weight: '65',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Shukla', subCaste: 'Saryupareen', motherTongue: 'Hindi',
    education: 'BCA', occupation: 'Web Developer', companyName: 'TCS', annualIncome: '₹9 Lakhs',
    fatherName: 'Ravi Shukla', motherName: 'Anita Shukla', siblings: 0,
    country: 'India', state: 'Uttar Pradesh', city: 'Varanasi',
    dateOfBirth: '1998-06-19', timeOfBirth: '12:30', placeOfBirth: 'Varanasi',
    rasi: 'Kumbha (Aquarius)', nakshatra: 'Dhanishtha', laknam: 'Kumbha', gothram: 'Atri', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Simha (Leo)', 'Dhanu (Sagittarius)', 'Tula (Libra)'],
    preferredNakshatra: ['Magha', 'Mula', 'Swati'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 22, prefAgeMax: 28, prefHeight: '5\'2" - 5\'6"', prefEducation: 'Graduate', prefLocation: 'Varanasi', prefReligion: 'Hindu',
  },
  {
    firstName: 'Shreya', lastName: 'Mishra', email: 'shreya@test.com', mobile: '9876543229',
    gender: 'female', fullName: 'Shreya Mishra', age: 28, height: '5\'6"', weight: '56',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Mishra', subCaste: 'Maithil', motherTongue: 'Hindi',
    education: 'MA English', occupation: 'Content Writer', companyName: 'Times Group', annualIncome: '₹8 Lakhs',
    fatherName: 'Arun Mishra', motherName: 'Neelam Mishra', siblings: 1,
    country: 'India', state: 'Bihar', city: 'Patna',
    dateOfBirth: '1996-10-05', timeOfBirth: '09:00', placeOfBirth: 'Patna',
    rasi: 'Mithuna (Gemini)', nakshatra: 'Ardra', laknam: 'Mithuna', gothram: 'Bharadwaja', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Dhanu (Sagittarius)', 'Kumbha (Aquarius)', 'Tula (Libra)'],
    preferredNakshatra: ['Mula', 'Dhanishtha', 'Swati'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 28, prefAgeMax: 34, prefHeight: '5\'7" - 6\'0"', prefEducation: 'Post Graduate', prefLocation: 'Patna', prefReligion: 'Hindu',
  },
  {
    firstName: 'Vivek', lastName: 'Pillai', email: 'vivek@test.com', mobile: '9876543230',
    gender: 'male', fullName: 'Vivek Pillai', age: 30, height: '5\'10"', weight: '74',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Pillai', subCaste: 'Vellalar', motherTongue: 'Tamil',
    education: 'M.Sc Physics', occupation: 'Research Scientist', companyName: 'ISRO', annualIncome: '₹24 Lakhs',
    fatherName: 'Muthu Pillai', motherName: 'Meenakshi Pillai', siblings: 0,
    country: 'India', state: 'Tamil Nadu', city: 'Coimbatore',
    dateOfBirth: '1994-04-28', timeOfBirth: '16:20', placeOfBirth: 'Coimbatore',
    rasi: 'Vrishchika (Scorpio)', nakshatra: 'Jyeshtha', laknam: 'Vrishchika', gothram: 'Vasishta', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Karka (Cancer)', 'Meena (Pisces)', 'Kanya (Virgo)'],
    preferredNakshatra: ['Pushya', 'Revati', 'Hasta'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 25, prefAgeMax: 31, prefHeight: '5\'3" - 5\'8"', prefEducation: 'Post Graduate', prefLocation: 'Coimbatore', prefReligion: 'Hindu',
  },
  {
    firstName: 'Ritu', lastName: 'Kapoor', email: 'ritu@test.com', mobile: '9876543231',
    gender: 'female', fullName: 'Ritu Kapoor', age: 30, height: '5\'7"', weight: '60',
    maritalStatus: 'Divorced', religion: 'Hindu', caste: 'Kapoor', subCaste: 'Punjabi', motherTongue: 'Hindi',
    education: 'MBA HR', occupation: 'HR Manager', companyName: 'Flipkart', annualIncome: '₹20 Lakhs',
    fatherName: 'Mohan Kapoor', motherName: 'Kiran Kapoor', siblings: 0,
    country: 'India', state: 'Haryana', city: 'Gurugram',
    dateOfBirth: '1994-08-15', timeOfBirth: '07:45', placeOfBirth: 'Chandigarh',
    rasi: 'Dhanu (Sagittarius)', nakshatra: 'Purva Ashadha', laknam: 'Dhanu', gothram: 'Angirasa', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Mithuna (Gemini)', 'Tula (Libra)', 'Kumbha (Aquarius)'],
    preferredNakshatra: ['Punarvasu', 'Swati', 'Dhanishtha'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 30, prefAgeMax: 38, prefHeight: '5\'8" - 6\'1"', prefEducation: 'Post Graduate', prefLocation: 'Gurugram', prefReligion: 'Any',
  },
  {
    firstName: 'Akash', lastName: 'Das', email: 'akash@test.com', mobile: '9876543232',
    gender: 'male', fullName: 'Akash Das', age: 27, height: '5\'9"', weight: '70',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Das', subCaste: 'Kayastha', motherTongue: 'Bengali',
    education: 'BBA', occupation: 'Sales Manager', companyName: 'BYJU\'s', annualIncome: '₹15 Lakhs',
    fatherName: 'Suman Das', motherName: 'Rina Das', siblings: 1,
    country: 'India', state: 'Odisha', city: 'Bhubaneswar',
    dateOfBirth: '1997-12-03', timeOfBirth: '10:30', placeOfBirth: 'Bhubaneswar',
    rasi: 'Meena (Pisces)', nakshatra: 'Revati', laknam: 'Meena', gothram: 'Gautama', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Karka (Cancer)', 'Vrishchika (Scorpio)', 'Kanya (Virgo)'],
    preferredNakshatra: ['Pushya', 'Jyeshtha', 'Hasta'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 23, prefAgeMax: 29, prefHeight: '5\'2" - 5\'7"', prefEducation: 'Graduate', prefLocation: 'Bhubaneswar', prefReligion: 'Hindu',
  },
  {
    firstName: 'Fatima', lastName: 'Sheikh', email: 'fatima@test.com', mobile: '9876543233',
    gender: 'female', fullName: 'Fatima Sheikh', age: 27, height: '5\'2"', weight: '55',
    maritalStatus: 'Never Married', religion: 'Muslim', caste: 'Sheikh', subCaste: 'Siddiqui', motherTongue: 'Urdu',
    education: 'B.Pharm', occupation: 'Pharmacist', companyName: 'Cipla', annualIncome: '₹7 Lakhs',
    fatherName: 'Irfan Sheikh', motherName: 'Zainab Sheikh', siblings: 2,
    country: 'India', state: 'Telangana', city: 'Hyderabad',
    dateOfBirth: '1997-05-20', timeOfBirth: '13:15', placeOfBirth: 'Hyderabad',
    rasi: 'Tula (Libra)', nakshatra: 'Chitra', laknam: 'Tula', gothram: 'Maitreya', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Mithuna (Gemini)', 'Kumbha (Aquarius)', 'Dhanu (Sagittarius)'],
    preferredNakshatra: ['Punarvasu', 'Dhanishtha', 'Mula'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 27, prefAgeMax: 34, prefHeight: '5\'6" - 5\'11"', prefEducation: 'Graduate', prefLocation: 'Hyderabad', prefReligion: 'Muslim',
  },
  {
    firstName: 'Gaurav', lastName: 'Thakur', email: 'gaurav@test.com', mobile: '9876543234',
    gender: 'male', fullName: 'Gaurav Thakur', age: 28, height: '6\'0"', weight: '78',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Thakur', subCaste: 'Kshatriya', motherTongue: 'Hindi',
    education: 'B.Tech Mechanical', occupation: 'IAS Officer', companyName: 'Government of India', annualIncome: '₹15 Lakhs',
    fatherName: 'Dharamvir Thakur', motherName: 'Suman Thakur', siblings: 2,
    country: 'India', state: 'Himachal Pradesh', city: 'Shimla',
    dateOfBirth: '1996-02-10', timeOfBirth: '05:30', placeOfBirth: 'Shimla',
    rasi: 'Kanya (Virgo)', nakshatra: 'Hasta', laknam: 'Kanya', gothram: 'Shandilya', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Vrishabha (Taurus)', 'Makara (Capricorn)', 'Meena (Pisces)'],
    preferredNakshatra: ['Rohini', 'Uttara Ashadha', 'Revati'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 24, prefAgeMax: 30, prefHeight: '5\'2" - 5\'8"', prefEducation: 'Graduate', prefLocation: 'Shimla', prefReligion: 'Hindu',
  },
  {
    firstName: 'Lakshmi', lastName: 'Rao', email: 'lakshmi@test.com', mobile: '9876543235',
    gender: 'female', fullName: 'Lakshmi Rao', age: 29, height: '5\'5"', weight: '58',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Rao', subCaste: 'Deshastha', motherTongue: 'Kannada',
    education: 'M.Sc Psychology', occupation: 'Clinical Psychologist', companyName: 'NIMHANS', annualIncome: '₹11 Lakhs',
    fatherName: 'Srinivas Rao', motherName: 'Anuradha Rao', siblings: 1,
    country: 'India', state: 'Karnataka', city: 'Mysore',
    dateOfBirth: '1995-09-08', timeOfBirth: '18:30', placeOfBirth: 'Mysore',
    rasi: 'Vrishabha (Taurus)', nakshatra: 'Mrigashira', laknam: 'Vrishabha', gothram: 'Garga', dhosham: 'Manglik / Chevvai Dhosham',
    horoscopeAvailable: true,
    preferredRasi: ['Kanya (Virgo)', 'Makara (Capricorn)', 'Mesha (Aries)'],
    preferredNakshatra: ['Hasta', 'Uttara Ashadha', 'Ashwini'],
    dhoshamPreference: 'Manglik / Chevvai Dhosham', horoscopeMatchRequired: true,
    prefAgeMin: 29, prefAgeMax: 36, prefHeight: '5\'8" - 6\'1"', prefEducation: 'Post Graduate', prefLocation: 'Mysore', prefReligion: 'Hindu',
  },
  {
    firstName: 'Ravi', lastName: 'Menon', email: 'ravi@test.com', mobile: '9876543236',
    gender: 'male', fullName: 'Ravi Menon', age: 34, height: '5\'8"', weight: '72',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Menon', subCaste: 'Nair', motherTongue: 'Malayalam',
    education: 'MS Software Engineering', occupation: 'Engineering Manager', companyName: 'Facebook', annualIncome: '₹60 Lakhs',
    fatherName: 'Krishnan Menon', motherName: 'Leela Menon', siblings: 1,
    country: 'India', state: 'Maharashtra', city: 'Mumbai',
    dateOfBirth: '1990-12-01', timeOfBirth: '04:50', placeOfBirth: 'Mumbai',
    rasi: 'Simha (Leo)', nakshatra: 'Purva Phalguni', laknam: 'Simha', gothram: 'Kashyapa', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Kanya (Virgo)', 'Vrishchika (Scorpio)', 'Meena (Pisces)'],
    preferredNakshatra: ['Hasta', 'Jyeshtha', 'Revati'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 27, prefAgeMax: 33, prefHeight: '5\'3" - 5\'8"', prefEducation: 'Graduate', prefLocation: 'Mumbai', prefReligion: 'Hindu',
  },
  {
    firstName: 'Sneha', lastName: 'Paul', email: 'sneha@test.com', mobile: '9876543237',
    gender: 'female', fullName: 'Sneha Paul', age: 22, height: '5\'4"', weight: '51',
    maritalStatus: 'Never Married', religion: 'Christian', caste: 'Paul', subCaste: 'Catholic', motherTongue: 'English',
    education: 'BBA', occupation: 'Marketing Executive', companyName: 'Tata Motors', annualIncome: '₹6 Lakhs',
    fatherName: 'James Paul', motherName: 'Mary Paul', siblings: 1,
    country: 'India', state: 'Goa', city: 'Panaji',
    dateOfBirth: '2002-06-30', timeOfBirth: '09:20', placeOfBirth: 'Panaji',
    rasi: 'Mithuna (Gemini)', nakshatra: 'Punarvasu', laknam: 'Mithuna', gothram: 'Maitreya', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Tula (Libra)', 'Kumbha (Aquarius)', 'Dhanu (Sagittarius)'],
    preferredNakshatra: ['Swati', 'Dhanishtha', 'Mula'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 24, prefAgeMax: 30, prefHeight: '5\'7" - 6\'0"', prefEducation: 'Graduate', prefLocation: 'Panaji', prefReligion: 'Christian',
  },
  {
    firstName: 'Nitin', lastName: 'Bose', email: 'nitin@test.com', mobile: '9876543238',
    gender: 'male', fullName: 'Nitin Bose', age: 32, height: '5\'9"', weight: '73',
    maritalStatus: 'Never Married', religion: 'Hindu', caste: 'Bose', subCaste: 'Kayastha', motherTongue: 'Bengali',
    education: 'LLB', occupation: 'Corporate Lawyer', companyName: 'Khaitan & Co', annualIncome: '₹28 Lakhs',
    fatherName: 'Subhas Bose', motherName: 'Deepali Bose', siblings: 1,
    country: 'India', state: 'Delhi', city: 'New Delhi',
    dateOfBirth: '1992-07-07', timeOfBirth: '15:10', placeOfBirth: 'New Delhi',
    rasi: 'Makara (Capricorn)', nakshatra: 'Shravana', laknam: 'Makara', gothram: 'Kaushika', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Karka (Cancer)', 'Vrishchika (Scorpio)', 'Meena (Pisces)'],
    preferredNakshatra: ['Pushya', 'Jyeshtha', 'Revati'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 26, prefAgeMax: 32, prefHeight: '5\'3" - 5\'9"', prefEducation: 'Post Graduate', prefLocation: 'New Delhi', prefReligion: 'Any',
  },
  {
    firstName: 'Divya', lastName: 'Chandran', email: 'divya@test.com', mobile: '9876543239',
    gender: 'female', fullName: 'Divya Chandran', age: 31, height: '5\'6"', weight: '59',
    maritalStatus: 'Widowed', religion: 'Hindu', caste: 'Chandran', subCaste: 'Nair', motherTongue: 'Malayalam',
    education: 'MBBS MS', occupation: 'Gynecologist', companyName: 'Motherhood Hospital', annualIncome: '₹30 Lakhs',
    fatherName: 'Keshav Chandran', motherName: 'Malini Chandran', siblings: 1,
    country: 'India', state: 'Kerala', city: 'Kozhikode',
    dateOfBirth: '1993-11-12', timeOfBirth: '12:00', placeOfBirth: 'Kozhikode',
    rasi: 'Karka (Cancer)', nakshatra: 'Ashlesha', laknam: 'Karka', gothram: 'Angirasa', dhosham: 'None',
    horoscopeAvailable: true,
    preferredRasi: ['Vrishchika (Scorpio)', 'Kumbha (Aquarius)', 'Mesha (Aries)'],
    preferredNakshatra: ['Jyeshtha', 'Dhanishtha', 'Ashwini'],
    dhoshamPreference: 'None', horoscopeMatchRequired: false,
    prefAgeMin: 32, prefAgeMax: 40, prefHeight: '5\'8" - 6\'1"', prefEducation: 'Post Graduate', prefLocation: 'Kozhikode', prefReligion: 'Hindu',
  },
];

async function seed() {
  const conn = await mysql.createConnection({
    host: process.env.DB_HOST || 'localhost',
    user: process.env.DB_USER || 'root',
    password: process.env.DB_PASSWORD || '',
    database: process.env.DB_NAME || 'matrimony',
  });

  const password = await bcrypt.hash('password123', SALT_ROUNDS);

  for (const data of seedData) {
    try {
      const [result] = await conn.execute(
        `INSERT INTO users (first_name, last_name, email, mobile, password, gender, subscription_type, viewed_profiles, last_viewed_reset)
         VALUES (?, ?, ?, ?, ?, ?, 'free', 0, NOW())`,
        [data.firstName, data.lastName, data.email, data.mobile, password, data.gender]
      );
      const userId = result.insertId;

      await conn.execute(
        `INSERT INTO profiles (
          user_id, full_name, age, height, weight,
          marital_status, religion, caste, sub_caste, mother_tongue,
          education, occupation, company_name, annual_income,
          father_name, mother_name, siblings,
          country, state, city,
          date_of_birth, time_of_birth, place_of_birth,
          rasi, nakshatra, laknam, gothram, dhosham,
          horoscope_available,
          preferred_rasi, preferred_nakshatra, dhosham_preference, horoscope_match_required,
          pref_age_min, pref_age_max, pref_height, pref_education, pref_location, pref_religion,
          profile_completed
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)`,
        [
          userId,
          data.fullName, data.age, data.height, data.weight,
          data.maritalStatus, data.religion, data.caste, data.subCaste, data.motherTongue,
          data.education, data.occupation, data.companyName, data.annualIncome,
          data.fatherName, data.motherName, data.siblings,
          data.country, data.state, data.city,
          data.dateOfBirth || null, data.timeOfBirth || null, data.placeOfBirth || null,
          data.rasi || null, data.nakshatra || null, data.laknam || null, data.gothram || null, data.dhosham || null,
          data.horoscopeAvailable ? 1 : 0,
          data.preferredRasi ? (Array.isArray(data.preferredRasi) ? JSON.stringify(data.preferredRasi) : data.preferredRasi) : null,
          data.preferredNakshatra ? (Array.isArray(data.preferredNakshatra) ? JSON.stringify(data.preferredNakshatra) : data.preferredNakshatra) : null,
          data.dhoshamPreference || null,
          data.horoscopeMatchRequired ? 1 : 0,
          data.prefAgeMin, data.prefAgeMax, data.prefHeight, data.prefEducation, data.prefLocation, data.prefReligion,
        ]
      );

      console.log(`✓ Created: ${data.fullName} (${data.gender}, ${data.age}) — ${data.email}`);
    } catch (err) {
      if (err.code === 'ER_DUP_ENTRY') {
        console.log(`→ Skipped (exists): ${data.email}`);
      } else {
        console.error(`✗ Error creating ${data.email}: ${err.message}`);
      }
    }
  }

  console.log('\nSeed complete!');
  await conn.end();
}

seed();
